import PDFDocument from 'pdfkit';
import { storageService } from './storage';

export interface ComplianceReportData {
  companyName: string;
  rcNumber: string;
  complianceScore: number;
  procurementReady: boolean;
  certificates: {
    name: string;
    certNumber: string;
    status: string;
    expiryDate: string;
    issuingAuthority: string;
  }[];
  generatedAt: Date;
  validUntil: Date;
}

export class PdfService {
  async generateComplianceReport(
    data: ComplianceReportData
  ): Promise<{ url: string; key: string }> {
    return new Promise((resolve, reject) => {
      try {
        // Create a PDF document
        const doc = new PDFDocument({ size: 'A4', margin: 50 });
        const chunks: Buffer[] = [];

        // Collect PDF chunks
        doc.on('data', (chunk) => chunks.push(chunk));
        doc.on('end', async () => {
          const pdfBuffer = Buffer.concat(chunks);
          const filename = `compliance-report-${data.rcNumber}-${Date.now()}.pdf`;

          // Upload to storage
          const result = await storageService.uploadFile(
            pdfBuffer,
            filename,
            'application/pdf',
            'reports'
          );

          resolve({ url: result.url, key: result.key });
        });

        doc.on('error', reject);

        // Add content to PDF
        this.addReportContent(doc, data);

        // Finalize PDF
        doc.end();
      } catch (error) {
        reject(error);
      }
    });
  }

  private addReportContent(doc: PDFKit.PDFDocument, data: ComplianceReportData): void {
    const {
      companyName,
      rcNumber,
      complianceScore,
      procurementReady,
      certificates,
      generatedAt,
      validUntil,
    } = data;

    // Header
    doc
      .fontSize(24)
      .font('Helvetica-Bold')
      .text('ClearPass Compliance Report', { align: 'center' });
    doc.moveDown();

    // Company Information
    doc.fontSize(14).font('Helvetica-Bold').text('Company Information');
    doc.fontSize(12).font('Helvetica').text(`Company Name: ${companyName}`);
    doc.text(`RC Number: ${rcNumber}`);
    doc.moveDown();

    // Compliance Score
    doc.fontSize(14).font('Helvetica-Bold').text('Compliance Score');
    doc.fontSize(12).font('Helvetica').text(`Overall Score: ${complianceScore}/100`);
    doc.text(`Procurement Ready: ${procurementReady ? 'Yes' : 'No'}`);
    doc.moveDown();

    // Certificates
    doc.fontSize(14).font('Helvetica-Bold').text('Certificates');
    certificates.forEach((cert, index) => {
      doc
        .fontSize(12)
        .font('Helvetica-Bold')
        .text(`${index + 1}. ${cert.name}`);
      doc.fontSize(10).font('Helvetica').text(`   Certificate Number: ${cert.certNumber}`);
      doc.text(`   Status: ${cert.status}`);
      doc.text(`   Expiry Date: ${cert.expiryDate}`);
      doc.text(`   Issuing Authority: ${cert.issuingAuthority}`);
      doc.moveDown(0.5);
    });

    // Footer
    doc.moveDown(2);
    doc
      .fontSize(10)
      .font('Helvetica')
      .text(`Generated: ${generatedAt.toLocaleDateString()}`, { align: 'center' });
    doc.text(`Valid Until: ${validUntil.toLocaleDateString()}`, { align: 'center' });
    doc.text('This report is automatically generated by ClearPass', { align: 'center' });
  }

  async generateCertificatePDF(certificateData: any): Promise<{ url: string; key: string }> {
    return new Promise((resolve, reject) => {
      try {
        const doc = new PDFDocument({ size: 'A4', margin: 50 });
        const chunks: Buffer[] = [];

        doc.on('data', (chunk) => chunks.push(chunk));
        doc.on('end', async () => {
          const pdfBuffer = Buffer.concat(chunks);
          const filename = `certificate-${certificateData.certNumber}-${Date.now()}.pdf`;

          const result = await storageService.uploadFile(
            pdfBuffer,
            filename,
            'application/pdf',
            'certificates'
          );

          resolve({ url: result.url, key: result.key });
        });

        doc.on('error', reject);

        // Add certificate content
        doc
          .fontSize(20)
          .font('Helvetica-Bold')
          .text('Certificate of Compliance', { align: 'center' });
        doc.moveDown();
        doc.fontSize(14).font('Helvetica').text(`Certificate Type: ${certificateData.name}`);
        doc.text(`Certificate Number: ${certificateData.certNumber}`);
        doc.text(`Status: ${certificateData.status}`);
        doc.text(`Issuing Authority: ${certificateData.issuingAuthority || 'N/A'}`);
        doc.text(`Issued Date: ${certificateData.issuedDate || 'N/A'}`);
        doc.text(`Expiry Date: ${certificateData.expiryDate || 'N/A'}`);
        doc.moveDown(2);
        doc.fontSize(10).font('Helvetica').text('Generated by ClearPass', { align: 'center' });

        doc.end();
      } catch (error) {
        reject(error);
      }
    });
  }
}

export const pdfService = new PdfService();
